### ISSUE TITLE
Does it support conditional probability on multiple variables?

### ISSUE THREAD

**Issue by gabechu** [ilyakava/sumproduct#10]
Thank you for putting this package, nice work!

I want to create a factor graph within which has a factor node consists something like this `P(X3 | X1, X2)`, that `X3` is a variable that depends on another two variables. Just wondered how to express such computation using the `Factor` class. Apologize if this is the wrong place to ask this.

**Comment by ilyakava** [comment]
Hi @gabechu, thanks for your kind words!

I think this graph describes what you are talking about, containing the `X2 | X3,X4` relationship in this case:

![graph in test.py](https://camo.githubusercontent.com/23c2cd5079b3a5a032ba5757667d548c911c2da3d0fc7dedf674076c1ca191e7/687474703a2f2f662e636c2e6c792f6974656d732f32503032316a32793341325131393146343531682f756e6e616d6564302e706e67)

The code to construct this graph is [here](https://github.com/ilyakava/sumproduct/blob/4a58e12d8ed1dc9b9706649c1d751b182e5199c9/test.py#L16-L50).

Let me know if this helps.

**Comment by gabechu** [comment]
Thanks @ilyakava , that's exactly the factor relationship I'm looking for. 

Mind if I ask another question. Should the above factor graph be a directed graph? At least for the test code you put, it seems you are testing a directed graph with factors of `P(X1|X2)` and `P(X2|X3, X4)`.

**Comment by ilyakava** [comment]
@gabechu Sure no problem!

The graphs in this code are undirected. Note how we set up:

```
# first index is x3, second index is x4, third index is x2
f234 = Factor('f234', np.array([
            [
                [0.3, 0.5, 0.2], [0.1, 0.1, 0.8]
            ], [
                [0.9, 0.05, 0.05], [0.2, 0.7, 0.1]
            ]
        ]))
```

This 2x2x3 table holds `P( X3 = 0 | X4 = 0, X2 = 0)` but also `P( X2 = 0 | X4 = 0, X3 = 0)` and `P( X4 = 0 | X3 = 0, X2 = 0)` and so on for the other states. That is how this table is used when later the marginals are asked for [here](https://github.com/ilyakava/sumproduct/blob/4a58e12d8ed1dc9b9706649c1d751b182e5199c9/test.py#L67-L78)

```
self.g.nodes['x1'].marginal()
self.g.nodes['x2'].marginal()
self.g.nodes['x3'].marginal()
self.g.nodes['x4'].marginal()
```

To make it directed, I think you would fill in this table with zeros in some entries that capture the dependence that you want to make independent.

Closing for now, feel free to reopen if you have further questions/issues!
