### ISSUE TITLE
Order of factor potential

### ISSUE THREAD

**Issue by qillbel** [ilyakava/sumproduct#7]
Dear Author,

I just learn the algorithm and would like to try with your code. However, I have question about how should I order the factor potential in your code. I tried to understand test.py, but failed to understand it. So, imagine that I have a factor graph as shown in the picture below. The dimension in each variable node is 5. How should I order the factor potential, especially for **fac_2** ?
![fg](https://user-images.githubusercontent.com/16984417/39831569-cff2528c-53bc-11e8-97c5-c0718fd1b0ed.png)

Pardon me for the simple question.

**Comment by ilyakava** [comment]
Hi @qillbel,

Thanks for using my code and thanks for your question.

The ordering of the factor potential depends on how you will add nodes to the graph; there are multiple right answers. Here is one right answer.

Suppose R has 2 states, T1 has 3 states, T2 has 4 states, and T3 has 5 states. Suppose all these states I just mentioned are the numbers 0,1,2,... . This is always true:
![](http://latex2png.com/output//latex_c2a504a84a559f121e7c665268c5d997.png)

Suppose you make the following choice:

![](http://latex2png.com/output//latex_cf63e7169b5da79c8499c012ef3535fe.png)

Then you would make a 4 dimensional array `mypotvals = np.zeros([2,3,4,5])` and fill it up. For instance in this case you could fill `mypotvals(0,1,2,3) = 0.2` which means:

![](http://latex2png.com/output//latex_0165d2f9430069c08edb35ae9b727228.png)

Then say you initialize: `myf = Factor('myf', mypotvals )`. Then you *need* to do the following:

```
g = FactorGraph(silent=True)

R = Variable('R', 2)
T1 = Variable('T1', 3)
T2 = Variable('T2', 4)
T3 = Variable('T3', 5)

g.add(myf)
g.append('myf', R)
g.append('myf', T1)
g.append('myf', T2)
g.append('myf', T3)
```

**Comment by qillbel** [comment]
Thank you very much for the easy explanation. I have better understanding of it now. However, how you check whether a factor graph is a valid factor graph or not? can a factor graph have only variable nodes as its leaves?

thank you again

**Comment by ilyakava** [comment]
Here is a question to that might answer your question. In your example, should `P(I,R,T1,S1,P1,C1,T2,S2,P2,C2,T3,S3,P3,C3) = fac_1(.) * fac_2(.) * fac_3(.) * fac_4(.) * fac_5(.) * fac_6(.) * fac_7(.) * fac_8(.) * fac_9(.) * fac_10(.) * fac_11(.)` for the belief propagation algorithm to make sense? If this isn't true, do the formulas for computing marginals via belief propagation still work?
