### ISSUE TITLE
How to deal with x2's probability in the example?

### ISSUE THREAD

**Issue by HuiQiu1982** [ilyakava/sumproduct#9]
In the example, x1's  marginals are computed only depend on p(x1 | x2)，but i think it should be sum of all case of p(x1 | x2)p(x2), which need p(x2) to be known first. Am i right?

    from sumproduct import Variable, Factor, FactorGraph
    import numpy as np

    g = FactorGraph(silent=True) # init the graph without message printouts
    x1 = Variable('x1', 2) # init a variable with 2 states
    x2 = Variable('x2', 3) # init a variable with 3 states
    f12 = Factor('f12', np.array([
      [0.8,0.2],
      [0.2,0.8],
      [0.5,0.5]
    ])) # create a factor, node potential for p(x1 | x2)
    # connect the parents to their children
    g.add(f12)
    g.append('f12', x2) # order must be the same as dimensions in factor potential!
    g.append('f12', x1) # note: f12 potential's shape is (3,2), i.e. (x2,x1)

    >>> g.compute_marginals()
    >>> g.nodes['x1'].marginal()
    array([ 0.5,  0.5])

**Comment by ilyakava** [comment]
Though it has been many years since I studied factor graphs, I don't disagree with your statement. When I wrote that example I didn't stop to consider whether the factor graph I created was sound (I just wanted to use all the salient commands in `sumproduct.py` in as few lines as possible). Perhaps there is some constraint that the product of all the factor functions φ should be the joint distribution for the whole graph?

**Comment by HuiQiu1982** [comment]
1) “ I don't disagree ...”means what i described is right ?
2) Since the comment is "potential for p(x1|x2)", not "p(x1,x2)", so i'm thinking that p(x2) has a deterministic power of whole joint distribution.

Or, would you provide me another complete example of this code? i want to learn and then use  sumproduct.py in my project. Thanks so much~

**Comment by gabechu** [comment]
@HuiQiu1982  I think I can answer your question.

If you want to set a prior to `X2` you can do it by creating another factor. Let's call the factor `prior`,
```
prior = Factor('Prior', np.array([0.3, 07]))

# connect prior with x2
g.add(prior)
g.append('prior', x2)
```
The corresponding graph regarding the whole computation then would be
```
prior --> X2 --> f12 --> X1
```

When no prior is assigned, the default is uniform.
